USE [master]
GO
/****** Object:  Database [BDProyecto]    Script Date: 6/11/2025 2:22:33 p. m. ******/
CREATE DATABASE [BDProyecto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDProyecto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BDProyecto.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDProyecto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BDProyecto_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BDProyecto] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDProyecto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BDProyecto] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BDProyecto] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BDProyecto] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BDProyecto] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BDProyecto] SET ARITHABORT OFF 
GO
ALTER DATABASE [BDProyecto] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BDProyecto] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDProyecto] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDProyecto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDProyecto] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BDProyecto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BDProyecto] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDProyecto] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BDProyecto] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDProyecto] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BDProyecto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDProyecto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDProyecto] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BDProyecto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BDProyecto] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDProyecto] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDProyecto] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BDProyecto] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BDProyecto] SET  MULTI_USER 
GO
ALTER DATABASE [BDProyecto] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BDProyecto] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BDProyecto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BDProyecto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BDProyecto] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BDProyecto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BDProyecto] SET QUERY_STORE = ON
GO
ALTER DATABASE [BDProyecto] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BDProyecto]
GO
/****** Object:  Table [dbo].[Emocion]    Script Date: 6/11/2025 2:22:34 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Emocion](
	[IdEmocion] [int] NOT NULL,
	[NombreEmocion] [nvarchar](30) NULL,
	[Tipo] [nvarchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEmocion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NivelBienestar]    Script Date: 6/11/2025 2:22:34 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NivelBienestar](
	[IdNivel] [int] NOT NULL,
	[IdUsuario] [int] NULL,
	[Puntaje] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdNivel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Registro]    Script Date: 6/11/2025 2:22:34 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Registro](
	[IdRegistro] [int] NOT NULL,
	[IdUsuario] [int] NULL,
	[IdEmocion] [int] NULL,
	[Fecha] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdRegistro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 6/11/2025 2:22:34 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[IdUsuario] [int] NOT NULL,
	[Nombre] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NivelBienestar]  WITH CHECK ADD FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
ALTER TABLE [dbo].[Registro]  WITH CHECK ADD FOREIGN KEY([IdEmocion])
REFERENCES [dbo].[Emocion] ([IdEmocion])
GO
ALTER TABLE [dbo].[Registro]  WITH CHECK ADD FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
USE [master]
GO
ALTER DATABASE [BDProyecto] SET  READ_WRITE 
GO
